name: Brett Goldstar
favicon: null
layout_spectrum: 0.50113
typography_spectrum: 0.286440598545596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#aa2015'
    - '#6d6d6d'
    - '#9f9f9f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
