name: Brett Goldstar
favicon: null
layout_spectrum: 0
typography_spectrum: 0.286440598545596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0c5bc'
    - '#66747b'
    - '#fefefe'
    - '#030302'
    - '#f33221'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
